gpu: drm: xylon: Fixed compile error
This patch comes from:
  https://github.com/Xilinx/linux-xlnx.git

Replace call to drm_fb_helper_restore_fbdev_mode() with
drm_fb_helper_restore_fbdev_mode_unlocked().

Error log:
drivers/gpu/drm/xylon/xylon_fbdev.c: In function 'xylon_drm_fbdev_restore_mode':
drivers/gpu/drm/xylon/xylon_fbdev.c:218:3: error: implicit declaration of
function 'drm_fb_helper_restore_fbdev_mode'
[-Werror=implicit-function-declaration]
   drm_fb_helper_restore_fbdev_mode(&fbdev->fb_helper);
   ^

Signed-off-by: Davor Joja <davorjoja@logicbricks.com>
Tested-by: Christian Kohn <christian.kohn@xilinx.com>
Signed-off-by: Michal Simek <michal.simek@xilinx.com>
(cherry picked from commit a63bb351cc7f044ced55d33ca36b8df82c833d93)
Signed-off-by: Zumeng Chen <zumeng.chen@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>