gpu: drm: xylon: Fixed compile error for kernel version 3.15
This patch comes from:
  https://github.com/Xilinx/linux-xlnx.git

Missing drm_framebuffer member in drm_crtc structure.

Error log:
drivers/gpu/drm/xylon/xylon_crtc.c: In function
'xylon_drm_crtc_mode_set':
drivers/gpu/drm/xylon/xylon_crtc.c:193:55: error: 'struct drm_crtc'
has no member named 'fb'
  ret = xylon_drm_plane_fb_set(crtc->private, base_crtc->fb,
                                                       ^
drivers/gpu/drm/xylon/xylon_crtc.c: In function
'xylon_drm_crtc_mode_set_base':
drivers/gpu/drm/xylon/xylon_crtc.c:211:55: error:
'struct drm_crtc' has no member named 'fb'
  ret = xylon_drm_plane_fb_set(crtc->private, base_crtc->fb,
                                                       ^
drivers/gpu/drm/xylon/xylon_crtc.c: In function
'xylon_drm_crtc_page_flip':
drivers/gpu/drm/xylon/xylon_crtc.c:308:11: error:
'struct drm_crtc' has no member named 'fb'
  base_crtc->fb = fb;
           ^
drivers/gpu/drm/xylon/xylon_crtc.c: In function
'xylon_drm_crtc_set_property':
drivers/gpu/drm/xylon/xylon_crtc.c:385:54: error:
'struct drm_crtc' has no member named 'fb'
   if (xylon_drm_plane_fb_set(crtc->private, base_crtc->fb,

Signed-off-by: Davor Joja <davorjoja@logicbricks.com>
Signed-off-by: Michal Simek <michal.simek@xilinx.com>
(cherry picked from commit b2f5a1831a8c3fa844884513d5a35d8cfb343011)
Signed-off-by: Zumeng Chen <zumeng.chen@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>