Fix the compilation error in MSI iova calculation
[Original patch taken from QorIQ-SDK-V1.6-SOURCE-20140619-yocto.iso]

There were couple of issue:
 - MSIIR address is uint64_t while it was passed to a function which expect
   this to dma_addr_t. And dma_addr_t can be 32 bit also.
 - do_div() expect uint64_t as first parameter while it was passed dma_addr_t.

Both of these changed be uint64_t.

Signed-off-by: Bharat Bhushan <bharat.bhushan@freescale.com>
Signed-off-by: Harninder Rai <harninder.rai@freescale.com>
Change-Id: Icca7eafef4fa63bc5daf355ebc0ba85a2111495a
Reviewed-on: http://git.am.freescale.net:8181/1732
Reviewed-by: Yoder Stuart-B08248 <stuart.yoder@freescale.com>
Reviewed-by: Fleming Andrew-AFLEMING <AFLEMING@freescale.com>
Tested-by: Fleming Andrew-AFLEMING <AFLEMING@freescale.com>