openvswitch:Fix the ovs_flow_mask_key() arguments missing issue in the datapath.c
The ovs_flow_cmd_new_or_set() is replaced by the ovs_flow_cmd_new() and
ovs_flow_cmd_set() two functions in the newer linux kernel.
The ovs_flow_mask_key() should to be updated in these functions.

It is based on the upstream commit 6f6e8414631dd4bde7e0e29e9cab41d7e7c92970.

The openvswitch kernel module compile failure information is as following:
==========================================================================
net/openvswitch/datapath.c: In function 'ovs_flow_cmd_new':
net/openvswitch/datapath.c:828:2: warning: the address of 'mask' will always evaluate as 'true' [-Waddress]
  ovs_flow_mask_key(&new_flow->key, &new_flow->unmasked_key, &mask);
  ^
net/openvswitch/datapath.c:828:2: error: too few arguments to function 'ovs_flow_mask_key'
In file included from net/openvswitch/datapath.h:30:0,from net/openvswitch/datapath.c:56:net/openvswitch/flow_table.h:84:6: note: declared here
 void ovs_flow_mask_key(struct sw_flow_key *dst, const struct sw_flow_key *src,
      ^
net/openvswitch/datapath.c: In function 'ovs_flow_cmd_set':
net/openvswitch/datapath.c:962:3: warning: the address of 'mask' will always evaluate as 'true' [-Waddress]
   ovs_flow_mask_key(&masked_key, &key, &mask);
   ^
net/openvswitch/datapath.c:962:3: error: too few arguments to function 'ovs_flow_mask_key'
In file included from net/openvswitch/datapath.h:30:0, from net/openvswitch/datapath.c:56:
net/openvswitch/flow_table.h:84:6: note: declared here
 void ovs_flow_mask_key(struct sw_flow_key *dst, const struct sw_flow_key *src,

Signed-off-by: Guojian Zhou <guojian.zhou@windriver.com>